/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeDemo */

#ifndef _Included_NativeDemo
#define _Included_NativeDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeDemo
 * Method:    sayHello
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT jint JNICALL Java_NativeDemo_sayHello
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
