/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jinspect_core_jvmti_JVMTICaller */

#ifndef _Included_org_jinspect_core_jvmti_JVMTICaller
#define _Included_org_jinspect_core_jvmti_JVMTICaller
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jinspect_core_jvmti_JVMTICaller
 * Method:    threadStartAndEndCallback
 * Signature: (Lorg/jinspect/core/jvmti/JVMTIListenerHandler;)V
 */
JNIEXPORT void JNICALL Java_org_jinspect_core_jvmti_JVMTICaller_threadStartAndEndCallback
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
